name: social_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  flutter_modular: ^4.3.1
  flex_color_scheme: ^4.1.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mocktail: ^0.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 200
        - asset: fonts/Montserrat-ThinItalic.ttf
          style: italic
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 300
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
        - asset: fonts/Montserrat-Light.ttf
          weight: 400
        - asset: fonts/Montserrat-LightItalic.ttf
          style: italic
        - asset: fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: fonts/Montserrat-MediumItalic.ttf
          style: italic
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: fonts/Montserrat-BoldItalic.ttf
          style: italic
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 900
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic